os: linux
dist: xenial
arch: amd64
language: ruby

jobs:
  include:
    - os: linux
      dist: focal
      arch: amd64
      script: true

    - os: linux
      dist: focal
      arch: Arm64
      script: true